import type { Job } from "@/types";

export const sampleJobs: Job[] = [
	{
		id: "1",
		title: "Frontend Developer",
		company: "Tech Innovations Ltd",
		location: "London, UK",
		description:
			"We are looking for a skilled Frontend Developer to join our dynamic team. You will be responsible for building user-facing web applications using modern JavaScript frameworks. The ideal candidate should have experience with React, TypeScript, and modern CSS frameworks.",
		requirements: [
			"3+ years of experience with JavaScript",
			"Proficiency in React or similar frameworks",
			"Experience with TypeScript",
			"Knowledge of CSS/SCSS and responsive design",
			"Familiarity with version control (Git)",
			"Bachelor's degree in Computer Science or related field",
		],
		skills: [
			"javascript",
			"react",
			"typescript",
			"css",
			"html",
			"git",
			"responsive design",
		],
		salary: {
			min: 45000,
			max: 65000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-15"),
		applicationUrl: "https://example.com/jobs/1",
		source: "company-website",
	},
	{
		id: "2",
		title: "Full Stack Developer",
		company: "StartupXYZ",
		location: "Remote",
		description:
			"Join our fast-growing startup as a Full Stack Developer. You'll work on both frontend and backend technologies, building scalable web applications. We use Node.js, React, and MongoDB in our tech stack.",
		requirements: [
			"5+ years of full-stack development experience",
			"Proficiency in Node.js and Express",
			"Strong React.js skills",
			"Experience with MongoDB or similar NoSQL databases",
			"Knowledge of RESTful API design",
			"Experience with cloud platforms (AWS preferred)",
		],
		skills: [
			"javascript",
			"nodejs",
			"react",
			"mongodb",
			"express",
			"aws",
			"restful-api",
		],
		salary: {
			min: 55000,
			max: 75000,
			currency: "GBP",
		},
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-20"),
		applicationUrl: "https://example.com/jobs/2",
		source: "linkedin",
	},
	{
		id: "3",
		title: "Python Developer",
		company: "Data Solutions Inc",
		location: "Manchester, UK",
		description:
			"We're seeking a Python Developer to work on data processing and web applications. You'll be working with Django, pandas, and various data analysis libraries. Experience with machine learning is a plus.",
		requirements: [
			"4+ years of Python development experience",
			"Proficiency in Django framework",
			"Experience with data analysis libraries (pandas, numpy)",
			"Knowledge of SQL databases (PostgreSQL preferred)",
			"Familiarity with machine learning concepts",
			"Strong problem-solving skills",
		],
		skills: [
			"python",
			"django",
			"pandas",
			"numpy",
			"postgresql",
			"sql",
			"machine learning",
		],
		salary: {
			min: 50000,
			max: 70000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-18"),
		applicationUrl: "https://example.com/jobs/3",
		source: "indeed",
	},
	{
		id: "4",
		title: "DevOps Engineer",
		company: "Cloud First Solutions",
		location: "Birmingham, UK",
		description:
			"Looking for a DevOps Engineer to help automate and streamline our development and deployment processes. You'll work with Docker, Kubernetes, and various cloud platforms to ensure reliable and scalable infrastructure.",
		requirements: [
			"3+ years of DevOps experience",
			"Proficiency with Docker and containerization",
			"Experience with Kubernetes orchestration",
			"Knowledge of CI/CD pipelines (Jenkins, GitLab CI)",
			"Familiarity with AWS or Azure",
			"Scripting skills (Bash, Python)",
		],
		skills: [
			"docker",
			"kubernetes",
			"aws",
			"jenkins",
			"python",
			"bash",
			"ci-cd",
		],
		salary: {
			min: 55000,
			max: 80000,
			currency: "GBP",
		},
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-22"),
		applicationUrl: "https://example.com/jobs/4",
		source: "company-website",
	},
	{
		id: "5",
		title: "Junior Software Developer",
		company: "Learning Tech Academy",
		location: "Edinburgh, UK",
		description:
			"Perfect opportunity for a recent graduate or career changer. You'll work alongside senior developers to build educational software applications. We provide comprehensive training and mentorship.",
		requirements: [
			"0-2 years of professional development experience",
			"Basic knowledge of JavaScript or Python",
			"Understanding of HTML/CSS",
			"Willingness to learn and adapt",
			"Strong communication skills",
			"Computer Science degree or coding bootcamp completion",
		],
		skills: ["javascript", "python", "html", "css", "git"],
		salary: {
			min: 25000,
			max: 35000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-25"),
		applicationUrl: "https://example.com/jobs/5",
		source: "graduate-jobs",
	},
	{
		id: "6",
		title: "React Native Developer",
		company: "Mobile Innovations",
		location: "London, UK",
		description:
			"We're looking for a React Native Developer to build cross-platform mobile applications. You'll work on consumer-facing apps with millions of users and collaborate with our design and product teams.",
		requirements: [
			"3+ years of React Native development",
			"Strong JavaScript and TypeScript skills",
			"Experience with mobile app deployment (App Store, Google Play)",
			"Knowledge of native mobile development (iOS/Android)",
			"Familiarity with Redux or similar state management",
			"Experience with mobile testing frameworks",
		],
		skills: [
			"react-native",
			"javascript",
			"typescript",
			"ios",
			"android",
			"redux",
			"mobile development",
		],
		salary: {
			min: 50000,
			max: 70000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-23"),
		applicationUrl: "https://example.com/jobs/6",
		source: "linkedin",
	},
	{
		id: "7",
		title: "Data Scientist",
		company: "Analytics Pro",
		location: "Remote",
		description:
			"Join our data science team to extract insights from large datasets. You'll work with machine learning algorithms, statistical analysis, and data visualization to solve business problems.",
		requirements: [
			"4+ years of data science experience",
			"Proficiency in Python and R",
			"Experience with machine learning libraries (scikit-learn, TensorFlow)",
			"Strong statistical analysis skills",
			"Experience with data visualization tools (Matplotlib, Tableau)",
			"Master's degree in Data Science, Statistics, or related field",
		],
		skills: [
			"python",
			"r",
			"machine learning",
			"tensorflow",
			"scikit-learn",
			"tableau",
			"statistics",
		],
		salary: {
			min: 60000,
			max: 85000,
			currency: "GBP",
		},
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-21"),
		applicationUrl: "https://example.com/jobs/7",
		source: "data-jobs",
	},
	{
		id: "8",
		title: "UI/UX Designer",
		company: "Creative Digital Agency",
		location: "Bristol, UK",
		description:
			"We're seeking a creative UI/UX Designer to design intuitive and engaging user interfaces. You'll work closely with developers and product managers to create exceptional user experiences.",
		requirements: [
			"3+ years of UI/UX design experience",
			"Proficiency in design tools (Figma, Sketch, Adobe Creative Suite)",
			"Strong understanding of user-centered design principles",
			"Experience with prototyping and wireframing",
			"Knowledge of web and mobile design best practices",
			"Portfolio demonstrating design skills",
		],
		skills: [
			"figma",
			"sketch",
			"adobe",
			"ui design",
			"ux design",
			"prototyping",
			"wireframing",
		],
		salary: {
			min: 40000,
			max: 55000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-19"),
		applicationUrl: "https://example.com/jobs/8",
		source: "design-jobs",
	},
	{
		id: "9",
		title: "Backend Developer (Java)",
		company: "Enterprise Solutions Ltd",
		location: "Leeds, UK",
		description:
			"Looking for an experienced Java Backend Developer to work on enterprise-level applications. You'll be responsible for building scalable microservices and maintaining existing systems.",
		requirements: [
			"5+ years of Java development experience",
			"Proficiency in Spring Framework",
			"Experience with microservices architecture",
			"Knowledge of SQL databases (Oracle, MySQL)",
			"Familiarity with message queues (RabbitMQ, Kafka)",
			"Experience with unit testing (JUnit)",
		],
		skills: [
			"java",
			"spring",
			"microservices",
			"mysql",
			"oracle",
			"rabbitmq",
			"junit",
		],
		salary: {
			min: 55000,
			max: 75000,
			currency: "GBP",
		},
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-17"),
		applicationUrl: "https://example.com/jobs/9",
		source: "company-website",
	},
	{
		id: "10",
		title: "Machine Learning Engineer",
		company: "AI Innovations Hub",
		location: "Cambridge, UK",
		description:
			"Join our AI team to develop and deploy machine learning models in production. You'll work on cutting-edge projects involving computer vision, NLP, and predictive analytics.",
		requirements: [
			"4+ years of machine learning experience",
			"Strong Python programming skills",
			"Experience with ML frameworks (TensorFlow, PyTorch)",
			"Knowledge of model deployment and MLOps",
			"Familiarity with cloud platforms (AWS, GCP)",
			"PhD or Master's in Machine Learning, AI, or related field",
		],
		skills: [
			"python",
			"machine learning",
			"tensorflow",
			"pytorch",
			"aws",
			"mlops",
			"computer vision",
			"nlp",
		],
		salary: {
			min: 70000,
			max: 95000,
			currency: "GBP",
		},
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-24"),
		applicationUrl: "https://example.com/jobs/10",
		source: "ai-jobs",
	},
	{
		id: "11",
		title: "Angular Developer",
		company: "Frontend Masters",
		location: "London, UK",
		description:
			"We're looking for an Angular Developer to build enterprise web applications. You'll work with large-scale Angular projects and collaborate with UX/UI designers.",
		requirements: [
			"4+ years of Angular development",
			"Strong TypeScript skills",
			"Experience with RxJS and NgRx",
			"Knowledge of Angular testing (Jasmine, Karma)",
			"Familiarity with Material Design",
		],
		skills: [
			"angular",
			"typescript",
			"rxjs",
			"ngrx",
			"jasmine",
			"karma",
			"material design",
		],
		salary: { min: 48000, max: 68000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-16"),
		applicationUrl: "https://example.com/jobs/11",
		source: "linkedin",
	},
	{
		id: "12",
		title: "Vue.js Developer",
		company: "Modern Web Solutions",
		location: "Remote",
		description:
			"Join our team to build modern web applications using Vue.js. You'll work on e-commerce platforms and content management systems.",
		requirements: [
			"3+ years Vue.js experience",
			"Knowledge of Vuex and Vue Router",
			"Experience with Nuxt.js",
			"Understanding of JavaScript ES6+",
		],
		skills: ["vue", "vuex", "nuxt", "javascript", "css", "html"],
		salary: { min: 42000, max: 62000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-14"),
		applicationUrl: "https://example.com/jobs/12",
		source: "company-website",
	},
	{
		id: "13",
		title: "iOS Developer (Swift)",
		company: "Mobile First",
		location: "Edinburgh, UK",
		description:
			"Looking for an iOS Developer to build native mobile applications. You'll work with the latest iOS technologies and App Store guidelines.",
		requirements: [
			"4+ years iOS development experience",
			"Proficiency in Swift and Objective-C",
			"Experience with UIKit and SwiftUI",
			"Knowledge of Core Data and networking",
		],
		skills: [
			"swift",
			"ios",
			"xcode",
			"uikit",
			"swiftui",
			"core data",
			"objective-c",
		],
		salary: { min: 52000, max: 72000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-13"),
		applicationUrl: "https://example.com/jobs/13",
		source: "apple-jobs",
	},
	{
		id: "14",
		title: "Android Developer (Kotlin)",
		company: "Android Experts",
		location: "Manchester, UK",
		description:
			"We're seeking an Android Developer to create high-quality mobile applications. Experience with Kotlin and modern Android architecture components required.",
		requirements: [
			"3+ years Android development",
			"Strong Kotlin programming skills",
			"Experience with Android Jetpack",
			"Knowledge of MVVM architecture",
		],
		skills: [
			"kotlin",
			"android",
			"jetpack",
			"mvvm",
			"room",
			"retrofit",
			"java",
		],
		salary: { min: 48000, max: 68000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-12"),
		applicationUrl: "https://example.com/jobs/14",
		source: "android-jobs",
	},
	{
		id: "15",
		title: "PHP Developer (Laravel)",
		company: "Web Development Co",
		location: "Birmingham, UK",
		description:
			"Join our web development team to build robust PHP applications using Laravel framework. You'll work on e-commerce and business applications.",
		requirements: [
			"4+ years PHP development",
			"Strong Laravel framework knowledge",
			"Experience with MySQL databases",
			"Understanding of MVC architecture",
		],
		skills: ["php", "laravel", "mysql", "blade", "composer", "artisan"],
		salary: { min: 40000, max: 58000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-11"),
		applicationUrl: "https://example.com/jobs/15",
		source: "php-jobs",
	},
	{
		id: "16",
		title: "Ruby on Rails Developer",
		company: "Rails Experts",
		location: "Remote",
		description:
			"We're looking for a Ruby on Rails Developer to maintain and extend our web applications. Experience with test-driven development is essential.",
		requirements: [
			"3+ years Rails development",
			"Strong Ruby programming skills",
			"Experience with RSpec testing",
			"Knowledge of PostgreSQL",
		],
		skills: ["ruby", "rails", "rspec", "postgresql", "sidekiq", "redis"],
		salary: { min: 45000, max: 65000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-10"),
		applicationUrl: "https://example.com/jobs/16",
		source: "ruby-jobs",
	},
	{
		id: "17",
		title: "C# .NET Developer",
		company: "Microsoft Solutions",
		location: "London, UK",
		description:
			"Looking for a C# .NET Developer to work on enterprise applications. You'll use the latest .NET technologies and work with Azure cloud services.",
		requirements: [
			"5+ years .NET development",
			"Strong C# programming skills",
			"Experience with ASP.NET Core",
			"Knowledge of Entity Framework",
		],
		skills: [
			"csharp",
			"dotnet",
			"aspnet",
			"entity framework",
			"azure",
			"sql server",
		],
		salary: { min: 55000, max: 75000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-09"),
		applicationUrl: "https://example.com/jobs/17",
		source: "microsoft-jobs",
	},
	{
		id: "18",
		title: "Go Developer",
		company: "Scalable Systems",
		location: "Remote",
		description:
			"Join our team to build high-performance backend services using Go. You'll work on distributed systems and microservices architecture.",
		requirements: [
			"3+ years Go programming",
			"Experience with microservices",
			"Knowledge of Docker and Kubernetes",
			"Understanding of concurrent programming",
		],
		skills: ["go", "microservices", "docker", "kubernetes", "grpc", "redis"],
		salary: { min: 58000, max: 78000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-08"),
		applicationUrl: "https://example.com/jobs/18",
		source: "golang-jobs",
	},
	{
		id: "19",
		title: "Rust Developer",
		company: "Systems Programming Inc",
		location: "Cambridge, UK",
		description:
			"We're seeking a Rust Developer to work on systems programming projects. You'll build high-performance, memory-safe applications.",
		requirements: [
			"2+ years Rust programming",
			"Strong systems programming background",
			"Understanding of memory management",
			"Experience with multithreading",
		],
		skills: ["rust", "systems programming", "cargo", "tokio", "serde"],
		salary: { min: 60000, max: 80000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-07"),
		applicationUrl: "https://example.com/jobs/19",
		source: "rust-jobs",
	},
	{
		id: "20",
		title: "Scala Developer",
		company: "Functional Programming Co",
		location: "London, UK",
		description:
			"Looking for a Scala Developer to work on big data processing applications. You'll use Akka, Spark, and other Scala ecosystem tools.",
		requirements: [
			"4+ years Scala development",
			"Experience with Akka framework",
			"Knowledge of Apache Spark",
			"Understanding of functional programming",
		],
		skills: ["scala", "akka", "spark", "functional programming", "kafka"],
		salary: { min: 62000, max: 82000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-06"),
		applicationUrl: "https://example.com/jobs/20",
		source: "scala-jobs",
	},
	{
		id: "21",
		title: "QA Engineer (Automation)",
		company: "Quality First",
		location: "Bristol, UK",
		description:
			"Join our QA team to develop automated testing frameworks. You'll work with Selenium, Cypress, and API testing tools.",
		requirements: [
			"3+ years QA automation experience",
			"Proficiency with Selenium WebDriver",
			"Experience with Cypress or similar tools",
			"Knowledge of API testing",
		],
		skills: [
			"selenium",
			"cypress",
			"api testing",
			"java",
			"javascript",
			"testng",
		],
		salary: { min: 42000, max: 58000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-05"),
		applicationUrl: "https://example.com/jobs/21",
		source: "qa-jobs",
	},
	{
		id: "22",
		title: "Security Engineer",
		company: "CyberSecure Ltd",
		location: "Remote",
		description:
			"We're looking for a Security Engineer to protect our systems and data. You'll work on penetration testing, vulnerability assessments, and security architecture.",
		requirements: [
			"4+ years cybersecurity experience",
			"Knowledge of OWASP top 10",
			"Experience with penetration testing tools",
			"Understanding of network security",
		],
		skills: [
			"cybersecurity",
			"penetration testing",
			"owasp",
			"burp suite",
			"nmap",
			"wireshark",
		],
		salary: { min: 58000, max: 78000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2024-01-04"),
		applicationUrl: "https://example.com/jobs/22",
		source: "security-jobs",
	},
	{
		id: "23",
		title: "Database Administrator",
		company: "Data Management Solutions",
		location: "Leeds, UK",
		description:
			"Looking for a Database Administrator to manage our database infrastructure. You'll work with PostgreSQL, MySQL, and MongoDB databases.",
		requirements: [
			"5+ years DBA experience",
			"Strong SQL skills",
			"Experience with database optimization",
			"Knowledge of backup and recovery procedures",
		],
		skills: [
			"sql",
			"postgresql",
			"mysql",
			"mongodb",
			"database optimization",
			"backup recovery",
		],
		salary: { min: 50000, max: 70000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-03"),
		applicationUrl: "https://example.com/jobs/23",
		source: "database-jobs",
	},
	{
		id: "24",
		title: "Cloud Architect (AWS)",
		company: "Cloud Solutions Inc",
		location: "London, UK",
		description:
			"We're seeking a Cloud Architect to design and implement AWS cloud solutions. You'll work on large-scale cloud migrations and infrastructure design.",
		requirements: [
			"6+ years cloud architecture experience",
			"AWS Solutions Architect certification",
			"Experience with infrastructure as code",
			"Knowledge of containerization",
		],
		skills: [
			"aws",
			"terraform",
			"cloudformation",
			"docker",
			"kubernetes",
			"lambda",
		],
		salary: { min: 75000, max: 95000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-02"),
		applicationUrl: "https://example.com/jobs/24",
		source: "cloud-jobs",
	},
	{
		id: "25",
		title: "Azure Developer",
		company: "Microsoft Partner",
		location: "Birmingham, UK",
		description:
			"Join our team to develop cloud applications on Microsoft Azure. You'll work with Azure Functions, Service Bus, and Cosmos DB.",
		requirements: [
			"4+ years Azure development",
			"Experience with Azure Functions",
			"Knowledge of Azure Service Bus",
			"Understanding of Azure DevOps",
		],
		skills: [
			"azure",
			"azure functions",
			"service bus",
			"cosmos db",
			"azure devops",
			"csharp",
		],
		salary: { min: 52000, max: 72000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2024-01-01"),
		applicationUrl: "https://example.com/jobs/25",
		source: "azure-jobs",
	},
	{
		id: "26",
		title: "Product Manager (Tech)",
		company: "Product Innovation Ltd",
		location: "London, UK",
		description:
			"We're looking for a Technical Product Manager to lead product development. You'll work closely with engineering teams and define product roadmaps.",
		requirements: [
			"5+ years product management experience",
			"Technical background preferred",
			"Experience with Agile methodologies",
			"Strong analytical skills",
		],
		skills: [
			"product management",
			"agile",
			"scrum",
			"roadmapping",
			"analytics",
			"user research",
		],
		salary: { min: 65000, max: 85000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-31"),
		applicationUrl: "https://example.com/jobs/26",
		source: "product-jobs",
	},
	{
		id: "27",
		title: "Scrum Master",
		company: "Agile Development Co",
		location: "Remote",
		description:
			"Join our team as a Scrum Master to facilitate agile development processes. You'll coach teams and remove impediments to delivery.",
		requirements: [
			"3+ years Scrum Master experience",
			"Certified Scrum Master (CSM)",
			"Experience with Jira and Confluence",
			"Strong facilitation skills",
		],
		skills: [
			"scrum",
			"agile",
			"jira",
			"confluence",
			"facilitation",
			"coaching",
		],
		salary: { min: 55000, max: 70000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-30"),
		applicationUrl: "https://example.com/jobs/27",
		source: "agile-jobs",
	},
	{
		id: "28",
		title: "Technical Writer",
		company: "Documentation Experts",
		location: "Edinburgh, UK",
		description:
			"We're seeking a Technical Writer to create developer documentation and API guides. You'll work with engineering teams to document complex systems.",
		requirements: [
			"3+ years technical writing experience",
			"Experience with API documentation",
			"Knowledge of Markdown and Git",
			"Understanding of software development",
		],
		skills: [
			"technical writing",
			"api documentation",
			"markdown",
			"git",
			"confluence",
		],
		salary: { min: 38000, max: 52000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-29"),
		applicationUrl: "https://example.com/jobs/28",
		source: "writing-jobs",
	},
	{
		id: "29",
		title: "Business Analyst (IT)",
		company: "Business Solutions Ltd",
		location: "Manchester, UK",
		description:
			"Looking for an IT Business Analyst to bridge the gap between business and technology. You'll gather requirements and define system specifications.",
		requirements: [
			"4+ years business analysis experience",
			"Experience with requirements gathering",
			"Knowledge of process modeling",
			"Understanding of software development lifecycle",
		],
		skills: [
			"business analysis",
			"requirements gathering",
			"process modeling",
			"visio",
			"sql",
		],
		salary: { min: 45000, max: 60000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-28"),
		applicationUrl: "https://example.com/jobs/29",
		source: "analyst-jobs",
	},
	{
		id: "30",
		title: "Systems Administrator",
		company: "IT Infrastructure Co",
		location: "Leeds, UK",
		description:
			"Join our IT team as a Systems Administrator to manage Linux and Windows servers. You'll handle system monitoring, backup, and maintenance.",
		requirements: [
			"4+ years systems administration",
			"Strong Linux and Windows knowledge",
			"Experience with virtualization",
			"Knowledge of network protocols",
		],
		skills: ["linux", "windows", "vmware", "networking", "bash", "powershell"],
		salary: { min: 40000, max: 55000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-27"),
		applicationUrl: "https://example.com/jobs/30",
		source: "sysadmin-jobs",
	},
	{
		id: "31",
		title: "Network Engineer",
		company: "Network Solutions Inc",
		location: "Bristol, UK",
		description:
			"We're looking for a Network Engineer to design and maintain network infrastructure. You'll work with Cisco equipment and network security.",
		requirements: [
			"5+ years network engineering",
			"CCNA or CCNP certification",
			"Experience with Cisco equipment",
			"Knowledge of network security",
		],
		skills: ["networking", "cisco", "ccna", "ccnp", "firewall", "vpn"],
		salary: { min: 48000, max: 65000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-26"),
		applicationUrl: "https://example.com/jobs/31",
		source: "network-jobs",
	},
	{
		id: "32",
		title: "Salesforce Developer",
		company: "CRM Solutions",
		location: "Remote",
		description:
			"Join our team to develop custom Salesforce solutions. You'll work with Apex, Lightning Components, and Salesforce integrations.",
		requirements: [
			"3+ years Salesforce development",
			"Platform Developer I certification",
			"Experience with Apex and SOQL",
			"Knowledge of Lightning framework",
		],
		skills: [
			"salesforce",
			"apex",
			"lightning",
			"soql",
			"visualforce",
			"integration",
		],
		salary: { min: 50000, max: 70000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-25"),
		applicationUrl: "https://example.com/jobs/32",
		source: "salesforce-jobs",
	},
	{
		id: "33",
		title: "WordPress Developer",
		company: "Web Design Agency",
		location: "London, UK",
		description:
			"We're seeking a WordPress Developer to create custom themes and plugins. You'll work on client websites and e-commerce solutions.",
		requirements: [
			"3+ years WordPress development",
			"Strong PHP and MySQL skills",
			"Experience with custom themes",
			"Knowledge of WooCommerce",
		],
		skills: ["wordpress", "php", "mysql", "woocommerce", "css", "javascript"],
		salary: { min: 35000, max: 50000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-24"),
		applicationUrl: "https://example.com/jobs/33",
		source: "wordpress-jobs",
	},
	{
		id: "34",
		title: "Shopify Developer",
		company: "E-commerce Solutions",
		location: "Birmingham, UK",
		description:
			"Looking for a Shopify Developer to create custom e-commerce solutions. You'll work with Liquid templating and Shopify APIs.",
		requirements: [
			"2+ years Shopify development",
			"Experience with Liquid templating",
			"Knowledge of Shopify APIs",
			"Understanding of e-commerce best practices",
		],
		skills: ["shopify", "liquid", "javascript", "css", "html", "e-commerce"],
		salary: { min: 38000, max: 55000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-23"),
		applicationUrl: "https://example.com/jobs/34",
		source: "ecommerce-jobs",
	},
	{
		id: "35",
		title: "Magento Developer",
		company: "Digital Commerce Ltd",
		location: "Remote",
		description:
			"Join our team to develop Magento e-commerce solutions. You'll work on custom modules and third-party integrations.",
		requirements: [
			"3+ years Magento development",
			"Strong PHP and MySQL skills",
			"Experience with Magento 2",
			"Knowledge of payment gateways",
		],
		skills: ["magento", "php", "mysql", "javascript", "payment integration"],
		salary: { min: 45000, max: 62000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-22"),
		applicationUrl: "https://example.com/jobs/35",
		source: "magento-jobs",
	},
	{
		id: "36",
		title: "Drupal Developer",
		company: "Content Management Pro",
		location: "Edinburgh, UK",
		description:
			"We're seeking a Drupal Developer to build content management systems. You'll work with custom modules and theming.",
		requirements: [
			"4+ years Drupal development",
			"Experience with Drupal 8/9",
			"Strong PHP skills",
			"Knowledge of Twig templating",
		],
		skills: ["drupal", "php", "twig", "mysql", "javascript", "css"],
		salary: { min: 42000, max: 58000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-21"),
		applicationUrl: "https://example.com/jobs/36",
		source: "drupal-jobs",
	},
	{
		id: "37",
		title: "Frontend Developer (Vue.js)",
		company: "Modern UI Solutions",
		location: "London, UK",
		description:
			"Looking for a Vue.js Frontend Developer to build responsive web applications. You'll work with modern CSS frameworks and component libraries.",
		requirements: [
			"3+ years Vue.js experience",
			"Strong JavaScript skills",
			"Experience with Vuetify or similar",
			"Knowledge of responsive design",
		],
		skills: [
			"vue",
			"javascript",
			"vuetify",
			"css",
			"html",
			"responsive design",
		],
		salary: { min: 46000, max: 64000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-20"),
		applicationUrl: "https://example.com/jobs/37",
		source: "vue-jobs",
	},
	{
		id: "38",
		title: "React Developer (Senior)",
		company: "Advanced Web Technologies",
		location: "Manchester, UK",
		description:
			"Join our team as a Senior React Developer to lead frontend development. You'll mentor junior developers and architect complex applications.",
		requirements: [
			"5+ years React development",
			"Experience with Redux and Context API",
			"Knowledge of React hooks",
			"Leadership experience",
		],
		skills: [
			"react",
			"redux",
			"javascript",
			"typescript",
			"leadership",
			"mentoring",
		],
		salary: { min: 58000, max: 78000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-19"),
		applicationUrl: "https://example.com/jobs/38",
		source: "react-jobs",
	},
	{
		id: "39",
		title: "Node.js Backend Developer",
		company: "API Solutions Inc",
		location: "Remote",
		description:
			"We're looking for a Node.js Backend Developer to build RESTful APIs and microservices. You'll work with Express.js and database optimization.",
		requirements: [
			"4+ years Node.js development",
			"Strong Express.js experience",
			"Knowledge of database design",
			"Experience with API development",
		],
		skills: [
			"nodejs",
			"express",
			"mongodb",
			"postgresql",
			"api development",
			"microservices",
		],
		salary: { min: 52000, max: 70000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-18"),
		applicationUrl: "https://example.com/jobs/39",
		source: "nodejs-jobs",
	},
	{
		id: "40",
		title: "Python Data Engineer",
		company: "Big Data Analytics",
		location: "Cambridge, UK",
		description:
			"Join our data engineering team to build data pipelines and ETL processes. You'll work with Apache Airflow and cloud data platforms.",
		requirements: [
			"4+ years Python experience",
			"Experience with Apache Airflow",
			"Knowledge of data warehousing",
			"Understanding of ETL processes",
		],
		skills: ["python", "airflow", "etl", "data warehousing", "pandas", "sql"],
		salary: { min: 55000, max: 75000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-17"),
		applicationUrl: "https://example.com/jobs/40",
		source: "data-engineering",
	},
	{
		id: "41",
		title: "Game Developer (Unity)",
		company: "Gaming Studio Ltd",
		location: "London, UK",
		description:
			"We're seeking a Unity Game Developer to create mobile and PC games. You'll work on game mechanics, UI, and performance optimization.",
		requirements: [
			"3+ years Unity development",
			"Strong C# programming skills",
			"Experience with game physics",
			"Knowledge of mobile optimization",
		],
		skills: [
			"unity",
			"csharp",
			"game development",
			"mobile optimization",
			"3d graphics",
		],
		salary: { min: 45000, max: 62000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-16"),
		applicationUrl: "https://example.com/jobs/41",
		source: "game-jobs",
	},
	{
		id: "42",
		title: "Blockchain Developer",
		company: "Crypto Solutions",
		location: "Remote",
		description:
			"Looking for a Blockchain Developer to work on DeFi applications. You'll develop smart contracts and web3 integrations.",
		requirements: [
			"2+ years blockchain development",
			"Experience with Solidity",
			"Knowledge of Ethereum ecosystem",
			"Understanding of DeFi protocols",
		],
		skills: [
			"blockchain",
			"solidity",
			"ethereum",
			"web3",
			"smart contracts",
			"defi",
		],
		salary: { min: 60000, max: 85000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-15"),
		applicationUrl: "https://example.com/jobs/42",
		source: "blockchain-jobs",
	},
	{
		id: "43",
		title: "AR/VR Developer",
		company: "Immersive Technologies",
		location: "Bristol, UK",
		description:
			"Join our team to develop AR/VR applications. You'll work with Unity 3D and create immersive experiences for various platforms.",
		requirements: [
			"3+ years AR/VR development",
			"Experience with Unity 3D",
			"Knowledge of ARKit/ARCore",
			"Understanding of 3D mathematics",
		],
		skills: ["ar", "vr", "unity", "arkit", "arcore", "3d development"],
		salary: { min: 50000, max: 70000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-14"),
		applicationUrl: "https://example.com/jobs/43",
		source: "arvr-jobs",
	},
	{
		id: "44",
		title: "Embedded Systems Developer",
		company: "IoT Solutions Inc",
		location: "Leeds, UK",
		description:
			"We're looking for an Embedded Systems Developer to work on IoT devices. You'll program microcontrollers and develop firmware.",
		requirements: [
			"4+ years embedded development",
			"Strong C/C++ skills",
			"Experience with microcontrollers",
			"Knowledge of real-time systems",
		],
		skills: [
			"embedded systems",
			"c",
			"cpp",
			"microcontrollers",
			"iot",
			"firmware",
		],
		salary: { min: 48000, max: 68000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-13"),
		applicationUrl: "https://example.com/jobs/44",
		source: "embedded-jobs",
	},
	{
		id: "45",
		title: "Site Reliability Engineer",
		company: "Reliable Systems Co",
		location: "Remote",
		description:
			"Join our SRE team to ensure system reliability and performance. You'll work on monitoring, alerting, and incident response.",
		requirements: [
			"4+ years SRE experience",
			"Strong Linux administration",
			"Experience with monitoring tools",
			"Knowledge of incident management",
		],
		skills: [
			"sre",
			"linux",
			"monitoring",
			"prometheus",
			"grafana",
			"incident response",
		],
		salary: { min: 58000, max: 80000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-12"),
		applicationUrl: "https://example.com/jobs/45",
		source: "sre-jobs",
	},
	{
		id: "46",
		title: "Flutter Developer",
		company: "Mobile Apps Ltd",
		location: "Edinburgh, UK",
		description:
			"We're seeking a Flutter Developer to build cross-platform mobile applications. You'll work with Dart and create beautiful UIs.",
		requirements: [
			"2+ years Flutter development",
			"Strong Dart programming skills",
			"Experience with Firebase",
			"Knowledge of mobile UI/UX",
		],
		skills: ["flutter", "dart", "firebase", "mobile development", "ui design"],
		salary: { min: 44000, max: 62000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-11"),
		applicationUrl: "https://example.com/jobs/46",
		source: "flutter-jobs",
	},
	{
		id: "47",
		title: "Xamarin Developer",
		company: "Cross-Platform Solutions",
		location: "Birmingham, UK",
		description:
			"Looking for a Xamarin Developer to create mobile applications for iOS and Android. You'll work with C# and XAML.",
		requirements: [
			"3+ years Xamarin development",
			"Strong C# skills",
			"Experience with XAML",
			"Knowledge of mobile platforms",
		],
		skills: [
			"xamarin",
			"csharp",
			"xaml",
			"mobile development",
			"ios",
			"android",
		],
		salary: { min: 46000, max: 64000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-10"),
		applicationUrl: "https://example.com/jobs/47",
		source: "xamarin-jobs",
	},
	{
		id: "48",
		title: "Cordova/PhoneGap Developer",
		company: "Hybrid Apps Co",
		location: "Remote",
		description:
			"Join our team to develop hybrid mobile applications using Cordova/PhoneGap. You'll work with web technologies for mobile platforms.",
		requirements: [
			"2+ years Cordova development",
			"Strong HTML, CSS, JavaScript",
			"Experience with mobile plugins",
			"Knowledge of app store deployment",
		],
		skills: [
			"cordova",
			"phonegap",
			"html",
			"css",
			"javascript",
			"mobile plugins",
		],
		salary: { min: 40000, max: 56000, currency: "GBP" },
		type: "full-time",
		remote: true,
		postedDate: new Date("2023-12-09"),
		applicationUrl: "https://example.com/jobs/48",
		source: "cordova-jobs",
	},
	{
		id: "49",
		title: "Ionic Developer",
		company: "Hybrid Mobile Solutions",
		location: "Manchester, UK",
		description:
			"We're looking for an Ionic Developer to build hybrid mobile applications. You'll work with Angular and Capacitor.",
		requirements: [
			"3+ years Ionic development",
			"Strong Angular skills",
			"Experience with Capacitor",
			"Knowledge of mobile UI components",
		],
		skills: [
			"ionic",
			"angular",
			"capacitor",
			"typescript",
			"mobile development",
		],
		salary: { min: 43000, max: 60000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-08"),
		applicationUrl: "https://example.com/jobs/49",
		source: "ionic-jobs",
	},
	{
		id: "50",
		title: "Progressive Web App Developer",
		company: "Modern Web Co",
		location: "London, UK",
		description:
			"Join our team to develop Progressive Web Applications. You'll work with service workers, web APIs, and offline functionality.",
		requirements: [
			"3+ years PWA development",
			"Experience with service workers",
			"Knowledge of web app manifest",
			"Understanding of offline storage",
		],
		skills: [
			"pwa",
			"service workers",
			"web apis",
			"offline storage",
			"javascript",
		],
		salary: { min: 47000, max: 65000, currency: "GBP" },
		type: "full-time",
		remote: false,
		postedDate: new Date("2023-12-07"),
		applicationUrl: "https://example.com/jobs/50",
		source: "pwa-jobs",
	},
];

// Generate additional jobs to reach 100+
const additionalJobTitles = [
	"GraphQL Developer",
	"Firebase Developer",
	"Strapi Developer",
	"Contentful Developer",
	"Headless CMS Developer",
	"JAMstack Developer",
	"Svelte Developer",
	"Solid.js Developer",
	"Qwik Developer",
	"Astro Developer",
	"Next.js Developer",
	"Nuxt.js Developer",
	"Gatsby Developer",
	"Remix Developer",
	"SvelteKit Developer",
	"Vite Developer",
	"Webpack Developer",
	"Rollup Developer",
	"Parcel Developer",
	"ESBuild Developer",
	"Babel Developer",
	"TypeScript Developer",
	"Flow Developer",
	"ReScript Developer",
	"PureScript Developer",
	"Elm Developer",
	"ClojureScript Developer",
	"Reason Developer",
	"F# Developer",
	"OCaml Developer",
	"Haskell Developer",
	"Erlang Developer",
	"Elixir Developer",
	"Crystal Developer",
	"Nim Developer",
	"Zig Developer",
	"Deno Developer",
	"Bun Developer",
	"Fresh Developer",
	"Tauri Developer",
	"Electron Developer",
	"Capacitor Developer",
	"NW.js Developer",
	"Neutralino Developer",
	"WebAssembly Developer",
	"Rust WASM Developer",
	"AssemblyScript Developer",
	"Emscripten Developer",
	"Three.js Developer",
	"Babylon.js Developer",
	"WebGL Developer",
	"WebXR Developer",
];

const companies = [
	"Tech Innovators Ltd",
	"Digital Solutions Inc",
	"Modern Development Co",
	"Future Tech Ltd",
	"Agile Systems",
	"Cloud Native Co",
	"Full Stack Solutions",
	"Microservices Ltd",
	"Data Driven Inc",
	"AI First Company",
	"Blockchain Ventures",
	"Quantum Computing Ltd",
	"Edge Computing Co",
	"Serverless Solutions",
	"Container Technologies",
	"DevOps Automation",
	"Security First Ltd",
	"Privacy Tech Inc",
	"Open Source Co",
	"Enterprise Solutions",
];

const locations = [
	"London, UK",
	"Manchester, UK",
	"Birmingham, UK",
	"Leeds, UK",
	"Edinburgh, UK",
	"Bristol, UK",
	"Cambridge, UK",
	"Oxford, UK",
	"Remote",
	"Glasgow, UK",
	"Liverpool, UK",
	"Sheffield, UK",
	"Newcastle, UK",
	"Nottingham, UK",
	"Cardiff, UK",
];

const skillSets = [
	["javascript", "typescript", "react", "node.js", "mongodb"],
	["python", "django", "flask", "postgresql", "redis"],
	["java", "spring", "hibernate", "maven", "junit"],
	["csharp", "dotnet", "entity framework", "azure", "sql server"],
	["go", "gin", "gorm", "docker", "kubernetes"],
	["rust", "actix", "tokio", "cargo", "wasm"],
	["php", "laravel", "symfony", "mysql", "composer"],
	["ruby", "rails", "rspec", "sidekiq", "postgresql"],
	["kotlin", "android", "jetpack", "room", "retrofit"],
	["swift", "ios", "uikit", "core data", "alamofire"],
];

// Generate jobs 51-100
for (let i = 51; i <= 100; i++) {
	const titleIndex = (i - 51) % additionalJobTitles.length;
	const companyIndex = (i - 51) % companies.length;
	const locationIndex = (i - 51) % locations.length;
	const skillSetIndex = (i - 51) % skillSets.length;

	const daysAgo = Math.floor(Math.random() * 60) + 1;
	const postedDate = new Date();
	postedDate.setDate(postedDate.getDate() - daysAgo);

	const minSalary = 35000 + Math.floor(Math.random() * 40000);
	const maxSalary = minSalary + 15000 + Math.floor(Math.random() * 25000);

	const isRemote = Math.random() > 0.6;
	const jobTypes: ("full-time" | "part-time" | "contract" | "internship")[] = [
		"full-time",
		"part-time",
		"contract",
		"internship",
	];
	const randomType = jobTypes[Math.floor(Math.random() * jobTypes.length)];

	sampleJobs.push({
		id: i.toString(),
		title: additionalJobTitles[titleIndex],
		company: companies[companyIndex],
		location: isRemote ? "Remote" : locations[locationIndex],
		description: `We are looking for an experienced ${additionalJobTitles[titleIndex]} to join our dynamic team. You will work on cutting-edge projects using modern technologies and contribute to our innovative solutions. This role offers excellent growth opportunities and the chance to work with the latest tools and frameworks.`,
		requirements: [
			`3+ years of relevant development experience`,
			`Strong programming and problem-solving skills`,
			`Experience with modern development tools and frameworks`,
			`Knowledge of software development best practices`,
			`Excellent communication and teamwork abilities`,
		],
		skills: skillSets[skillSetIndex],
		salary: {
			min: minSalary,
			max: maxSalary,
			currency: "GBP",
		},
		type: randomType,
		remote: isRemote,
		postedDate: postedDate,
		applicationUrl: `https://example.com/jobs/${i}`,
		source: "job-board",
	});
}
